### ISSUE TITLE
java.lang.NoSuchMethodError: 'java.util.Iterator okhttp3.Headers.iterator()'

### ISSUE THREAD

**Issue by lifengzhai** [aliyun/aliyun-ccp#295]
Sun Jun 14 15:06:02 CST 2020
There was an unexpected error (type=Internal Server Error, status=500).
'java.util.Iterator okhttp3.Headers.iterator()'
java.lang.NoSuchMethodError: 'java.util.Iterator okhttp3.Headers.iterator()'
	at com.aliyun.tea.TeaResponse.<init>(TeaResponse.java:30)
	at com.aliyun.tea.Tea.doAction(Tea.java:67)
	at com.aliyun.ccp.ccpclient.Client.getCaptcha(Client.java:827)

```
    public TeaResponse(Response response) {
        headers = new HashMap<>();
        this.response = response;
        statusCode = response.code();
        statusMessage = response.message();
        body = response.body().byteStream();
        Iterator<Pair<String, String>> headers = response.headers().iterator();
        Pair<String, String> pair;
        while (headers.hasNext()) {
            pair = headers.next();
            this.headers.put(pair.getFirst(), pair.getSecond());
        }
    }
```

**Comment by lifengzhai** [comment]
I solved this problem by upgrading the version of okhttp3.
